version: '3'
services:
  mysql:
    container_name: mysql8
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msproject

  redis:
    container_name: redis6
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"

  etcd:
    container_name: etcd3
    image: bitnami/etcd:3.5
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
      - "2380:2380"