server:
  name: "api"
  addr: "127.0.0.1:8080"

etcd:
  addrs:
    - "127.0.0.1:2379"

log:
  level: "info"
  format: "json"
  output: "both"
  file_path: "logs/api.log"
  max_size: 100
  max_backups: 3
  max_age: 30
  compress: true