server:
  name: "auth"
  addr: "0.0.0.0:8999"

grpc_server:
  addr: "0.0.0.0:8081"
  name: "auth"
  version: "v1.0.0"
  weight: 10

mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: mysproject

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

etcd:
  addrs:
    - "127.0.0.1:2379"

log:
  level: "info"